# Change these first
owner: StellarTechLab # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Mindscape Prod
    url: https://web.mindscapeapp.io
  - name: Mindscape Stage
    url: https://web.stg.mindscapeapp.io
  - name: API-BE Stage
    url: $API_BE_STAGE
  - name: Test Broken Site
    url: https://web.stg.mindscapeapp.io
    assignees:
      - ant-on-stellar

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.uselest.com
  # baseUrl: /your-repo-name
  logoUrl: https://web.mindscapeapp.io/icons/Icon-192.png
  name: Upptime
  introTitle: "**Uptime** status page"
  introMessage: This is a sample status page
  robotsText: "User-agent: * \n Disallow: /"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

commitMessages:
  commitAuthorName: "ant-on-stellar"
  commitAuthorEmail: "157169278+ant-on-stellar@users.noreply.github.com"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
